imports:
  resource: '../../src/Main/Routes/MainRoutes.yml'

home:
  path: /
  defaults: { _controller: 'Main\Controllers\HomeController::ourPage' }

homeHome:
  path: /home 
  defaults: { _controller: 'Main\Controllers\HomeController::ourPage' }

form_test:
  path: /form/test
  defaults: { _controller: 'Main\Controllers\HomeController::formTest' }

login_view:
  path: /login
  defaults: { _controller: 'Users\Controllers\LoginController::login' }

login:
  path: /login/check
  defaults: { _controller: 'Users\Controllers\LoginController::loginAction' }
  methods: [POST]