#!/usr/bin/env php
<?php

set_time_limit(0);

use Rhodium\Commands\CreateUser;
use Rhodium\Commands\CreateView;
use Rhodium\Commands\CreateModel;
use Rhodium\Commands\CreateRoute;
use Rhodium\Commands\CreateTable;
use Rhodium\Commands\CreateBundle;
use Rhodium\Commands\CreateController;

$app = require_once __DIR__.'/silex.php';

$application = $app['console'];
$application->add( new CreateUser() );
$application->add( new CreateView() );
$application->add( new CreateTable() );
$application->add( new CreateModel() );
$application->add( new CreateRoute() );
$application->add( new CreateBundle() );
$application->add( new CreateController() );

$application->add( new \Doctrine\DBAL\Tools\Console\Command\RunSqlCommand() );
$application->add( new \Doctrine\DBAL\Tools\Console\Command\ImportCommand() );

// ORM Commands
$application->add( new \Doctrine\ORM\Tools\Console\Command\ClearCache\MetadataCommand() );
$application->add( new \Doctrine\ORM\Tools\Console\Command\ClearCache\ResultCommand() );
$application->add( new \Doctrine\ORM\Tools\Console\Command\ClearCache\QueryCommand() );
$application->add( new \Doctrine\ORM\Tools\Console\Command\SchemaTool\CreateCommand() );
$application->add( new \Doctrine\ORM\Tools\Console\Command\SchemaTool\UpdateCommand() );
$application->add( new \Doctrine\ORM\Tools\Console\Command\SchemaTool\DropCommand() );
$application->add( new \Doctrine\ORM\Tools\Console\Command\EnsureProductionSettingsCommand() );
$application->add( new \Doctrine\ORM\Tools\Console\Command\ConvertDoctrine1SchemaCommand() );
$application->add( new \Doctrine\ORM\Tools\Console\Command\GenerateRepositoriesCommand() );
$application->add( new \Doctrine\ORM\Tools\Console\Command\GenerateEntitiesCommand() );
$application->add( new \Doctrine\ORM\Tools\Console\Command\GenerateProxiesCommand() );
$application->add( new \Doctrine\ORM\Tools\Console\Command\ConvertMappingCommand() );
$application->add( new \Doctrine\ORM\Tools\Console\Command\RunDqlCommand() );
$application->add( new \Doctrine\ORM\Tools\Console\Command\ValidateSchemaCommand() );

$application->run();