#!/usr/bin/env php
<?php

set_time_limit(0);

use Rhodium\Commands\FetchBundle;
use Rhodium\Commands\CreateController;

$app = require_once __DIR__.'/silex.php';

$application = $app['console'];
$application->add( new FetchBundle() );
$application->add( new CreateController() );

$application->run();