#!/usr/bin/env php

<?php

//include __DIR__.'/../bootstrap.php';
include __DIR__.'/../silex.php';

use \Doctrine\DBAL\Tools\Console\Command\RunSqlCommand;
use \Doctrine\DBAL\Tools\Console\Command\ImportCommand;

// ORM Commands
use \Doctrine\ORM\Tools\Console\Command\ClearCache\MetadataCommand;
use \Doctrine\ORM\Tools\Console\Command\ClearCache\ResultCommand;
use \Doctrine\ORM\Tools\Console\Command\ClearCache\QueryCommand;
use \Doctrine\ORM\Tools\Console\Command\SchemaTool\CreateCommand;
use \Doctrine\ORM\Tools\Console\Command\SchemaTool\UpdateCommand;
use \Doctrine\ORM\Tools\Console\Command\SchemaTool\DropCommand;
use \Doctrine\ORM\Tools\Console\Command\EnsureProductionSettingsCommand;
use \Doctrine\ORM\Tools\Console\Command\ConvertDoctrine1SchemaCommand;
use \Doctrine\ORM\Tools\Console\Command\GenerateRepositoriesCommand;
use \Doctrine\ORM\Tools\Console\Command\GenerateEntitiesCommand;
use \Doctrine\ORM\Tools\Console\Command\GenerateProxiesCommand;
use \Doctrine\ORM\Tools\Console\Command\ConvertMappingCommand;
use \Doctrine\ORM\Tools\Console\Command\RunDqlCommand;
use \Doctrine\ORM\Tools\Console\Command\ValidateSchemaCommand;

$helpers = array(
    'db' => new \Doctrine\DBAL\Tools\Console\Helper\ConnectionHelper($em->getConnection()),
    'em' => new \Doctrine\ORM\Tools\Console\Helper\EntityManagerHelper($em)
);

$cli = new \Symfony\Component\Console\Application('Doctrine Command Line Interface', Doctrine\Common\Version::VERSION);
$cli->setCatchExceptions(true);
$helperSet = $cli->getHelperSet();
foreach ($helpers as $name => $helper) {
    $helperSet->set($helper, $name);
}
$cli->addCommands(array(
    // DBAL Commands
    new \Doctrine\DBAL\Tools\Console\Command\RunSqlCommand(),
    new \Doctrine\DBAL\Tools\Console\Command\ImportCommand(),

    // ORM Commands
    new \Doctrine\ORM\Tools\Console\Command\ClearCache\MetadataCommand(),
    new \Doctrine\ORM\Tools\Console\Command\ClearCache\ResultCommand(),
    new \Doctrine\ORM\Tools\Console\Command\ClearCache\QueryCommand(),
    new \Doctrine\ORM\Tools\Console\Command\SchemaTool\CreateCommand(),
    new \Doctrine\ORM\Tools\Console\Command\SchemaTool\UpdateCommand(),
    new \Doctrine\ORM\Tools\Console\Command\SchemaTool\DropCommand(),
    new \Doctrine\ORM\Tools\Console\Command\EnsureProductionSettingsCommand(),
    new \Doctrine\ORM\Tools\Console\Command\ConvertDoctrine1SchemaCommand(),
    new \Doctrine\ORM\Tools\Console\Command\GenerateRepositoriesCommand(),
    new \Doctrine\ORM\Tools\Console\Command\GenerateEntitiesCommand(),
    new \Doctrine\ORM\Tools\Console\Command\GenerateProxiesCommand(),
    new \Doctrine\ORM\Tools\Console\Command\ConvertMappingCommand(),
    new \Doctrine\ORM\Tools\Console\Command\RunDqlCommand(),
    new \Doctrine\ORM\Tools\Console\Command\ValidateSchemaCommand(),

));
$cli->run();